1
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/1;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/1;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/1/1_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/1/1_2.fq.gz
10
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/10;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/10;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/10/10_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/10/10_2.fq.gz
11
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/11;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/11;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/11/11_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/11/11_2.fq.gz
12
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/12;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/12;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/12/12_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/12/12_2.fq.gz
13
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/13;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/13;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/13/13_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/13/13_2.fq.gz
14
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/14;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/14;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/14/14_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/14/14_2.fq.gz
15
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/15;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/15;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/15/15_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/15/15_2.fq.gz
16
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/16;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/16;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/16/16_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/16/16_2.fq.gz
17
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/17;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/17;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/17/17_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/17/17_2.fq.gz
18
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/18;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/18;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/18/18_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/18/18_2.fq.gz
19
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/19;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/19;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/19/19_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/19/19_2.fq.gz
2
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/2;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/2;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/2/2_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/2/2_2.fq.gz
20
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/20;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/20;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/20/20_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/20/20_2.fq.gz
21
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/21;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/21;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/21/21_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/21/21_2.fq.gz
22
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/22;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/22;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/22/22_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/22/22_2.fq.gz
23
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/23;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/23;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/23/23_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/23/23_2.fq.gz
24
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/24;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/24;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/24/24_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/24/24_2.fq.gz
25
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/25;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/25;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/25/25_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/25/25_2.fq.gz
26
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/26;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/26;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/26/26_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/26/26_2.fq.gz
27
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/27;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/27;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/27/27_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/27/27_2.fq.gz
28
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/28;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/28;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/28/28_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/28/28_2.fq.gz
29
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/29;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/29;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/29/29_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/29/29_2.fq.gz
3
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/3;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/3;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/3/3_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/3/3_2.fq.gz
30
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/30;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/30;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/30/30_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/30/30_2.fq.gz
31
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/31;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/31;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/31/31_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/31/31_2.fq.gz
32
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/32;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/32;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/32/32_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/32/32_2.fq.gz
33
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/33;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/33;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/33/33_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/33/33_2.fq.gz
34
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/34;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/34;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/34/34_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/34/34_2.fq.gz
35
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/35;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/35;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/35/35_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/35/35_2.fq.gz
36
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/36;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/36;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/36/36_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/36/36_2.fq.gz
37
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/37;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/37;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/37/37_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/37/37_2.fq.gz
38
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/38;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/38;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/38/38_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/38/38_2.fq.gz
39
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/39;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/39;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/39/39_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/39/39_2.fq.gz
4
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/4;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/4;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/4/4_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/4/4_2.fq.gz
5
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/5;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/5;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/5/5_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/5/5_2.fq.gz
6
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/6;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/6;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/6/6_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/6/6_2.fq.gz
7
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/7;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/7;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/7/7_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/7/7_2.fq.gz
8
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/8;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/8;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/8/8_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/8/8_2.fq.gz
9
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/9;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/9;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/9/9_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/9/9_2.fq.gz
F1
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/F1;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/F1;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/F1/F1_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/F1/F1_2.fq.gz
M1
mkdir /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/M1;cd /its1/GB_BT2/jianzuoyi/projects/Chicken/00.data/F17KTSCCWLJ0666_GALbwiR/Clean/M1;ls *_1.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/M1/M1_1.fq.gz;ls *_2.fq.gz | xargs zcat | gzip -c > /its1/GB_BT2/jianzuoyi/projects/Chicken/20.processing_for_gatk/merge_data/M1/M1_2.fq.gz
