bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/1/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/10/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/11/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/12/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/13/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/14/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/15/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/16/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/17/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/18/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/19/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/2/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/20/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/21/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/22/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/23/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/24/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/25/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/26/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/27/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/28/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/29/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/3/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/30/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/31/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/32/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/33/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/34/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/35/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/36/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/37/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/38/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/39/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/4/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/5/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/6/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/7/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/8/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/9/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/F1/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/M1/call_snp.sh
