/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/1/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/10/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/11/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/12/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/13/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/14/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/15/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/16/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/17/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/18/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/19/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/2/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/20/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/21/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/22/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/23/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/24/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/25/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/26/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/27/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/28/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/29/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/3/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/30/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/31/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/32/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/33/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/34/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/35/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/36/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/37/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/38/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/39/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/4/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/5/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/6/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/7/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/8/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/9/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/F1/call_snp.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE2/M1/call_snp.sh
