bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/28/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/29/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/3/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/30/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/31/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/32/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/33/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/34/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/35/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/36/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/37/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/38/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/39/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/4/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/5/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/6/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/7/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/8/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/9/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/F1/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/M1/call_snp.sh
