bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/1/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/10/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/11/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/12/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/13/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/14/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/15/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/16/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/17/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/18/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/19/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/2/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/20/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/21/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/22/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/23/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/24/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/25/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/26/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/27/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/28/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/29/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/3/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/30/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/31/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/32/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/33/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/34/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/35/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/36/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/37/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/38/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/39/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/4/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/5/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/6/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/7/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/8/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/9/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/F1/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/M1/call_snp.sh
