bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/1/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/10/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/11/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/12/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/13/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/14/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/15/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/16/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/17/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/18/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/19/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/2/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/20/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/21/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/22/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/23/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/24/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/25/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/26/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample/27/call_snp.sh
