bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/F1/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/M1/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/28/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/29/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/3/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/30/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/31/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/32/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/33/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/34/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/35/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/36/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/37/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/38/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/39/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/4/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/5/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/6/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/7/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/8/call_snp.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/80.speedseq/Sample.SGE/9/call_snp.sh
