bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_F1.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_M1.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_1.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_10.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_11.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_12.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_13.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_14.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_15.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_16.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_17.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_18.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_19.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_2.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_20.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_21.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_22.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_23.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_24.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_25.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_26.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_27.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_28.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_29.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_3.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_30.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_31.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_32.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_33.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_34.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_35.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_36.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_37.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_38.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_39.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_4.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_5.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_6.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_7.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_8.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step8.shell/ApplyBQSR_9.sh
