bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.1.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.10.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.11.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.12.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.13.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.14.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.15.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.16.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.17.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.18.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.19.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.2.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.20.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.21.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.22.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.23.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.24.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.25.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.26.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.27.sh
