bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.30.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.31.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.32.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.33.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.34.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.35.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.36.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.37.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.38.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.39.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.4.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.5.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.6.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.7.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.8.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.9.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.F1.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.M1.sh
