bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/10.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/11.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/12.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/13.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/14.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/15.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/16.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/17.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/18.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/19.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/2.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/20.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/21.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/22.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/23.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/24.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/25.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/26.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/27.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/28.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/29.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/3.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/30.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/31.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/32.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/33.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/34.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/35.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/36.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/37.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/38.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/39.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/4.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/5.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/6.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/7.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/8.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/9.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/F1.SortSam.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step5.shell/M1.SortSam.sh
