bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.1.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.10.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.11.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.12.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.13.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.14.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.15.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.16.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.17.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.18.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.19.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.2.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.20.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.21.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.22.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.23.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.24.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.25.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.26.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.27.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.28.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.29.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.3.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.30.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.31.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.32.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.33.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.34.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.35.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.36.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.37.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.38.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.39.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.4.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.5.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.6.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.7.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.8.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.9.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.F1.sh
bash /its1/GB_BT2/jianzuoyi/projects/Chicken/40.steps/step3.shell/MergeBamAlignment.M1.sh
