/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/10/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/11/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/12/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/13/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/14/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/15/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/16/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/17/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/18/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/19/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/1/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/20/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/21/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/22/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/23/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/24/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/25/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/26/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/27/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/28/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/29/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/2/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/30/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/31/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/32/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/33/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/34/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/35/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/36/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/37/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/38/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/39/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/3/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/4/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/5/run_gatk4.sh
#/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/6/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/7/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/8/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/9/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/F1/run_gatk4.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/60.gatk_sge/samples/M1/run_gatk4.sh
