/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/1/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/10/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/11/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/12/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/13/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/14/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/15/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/16/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/17/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/18/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/19/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/2/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/20/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/21/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/22/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/23/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/24/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/25/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/26/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/27/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/28/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/29/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/3/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/30/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/31/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/32/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/33/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/34/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/35/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/36/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/37/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/38/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/39/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/4/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/5/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/6/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/7/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/8/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/9/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/F1/run_process_data.sh
/its1/GB_BT2/jianzuoyi/projects/Chicken/30.gatk_data_processing/shell/M1/run_process_data.sh
